spring.application.name=config-server
server.port=8888

# GitHub backed config repo
# Ek alag GitHub repo banao: cartflow-config
# Usme har service ke liye alag .properties file hogi
# e.g. auth-service.properties, eureka-server.properties
spring.cloud.config.server.git.uri=https://github.com/mddeepa222/ecommerce-service-platform
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true

# Actuator endpoints
management.endpoints.web.exposure.include=health,info,refresh
